<?php


/*
* Implementation of hook_menu()
*/

/*function image_rotate_menu() {

  $items['imagerotate/%'] = array (
    'page callback' => 'image_rotate_get_image',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;

}*/



/*
 * implementation of hook_theme()
 */

//@TODO Cleanup
//@TODO pfade für fonts im moudl selbs und images sollten in files ... verschoben werden

function image_rotate_theme() {

  global $base_url;

  //Header ("Content-type: image/png");

  $im = imagecreate (100, 400);

  $black = ImageColorAllocate ($im, 0, 0, 0);
  $white = ImageColorAllocate ($im, 255, 255, 255);
  $grey = ImageColorAllocate ($im, 128, 128, 128);


  $path = drupal_get_path('module', 'image_rotate');

  //the absolute path http://www.goobar.de/foo/bar..
  //$font  = "$base_url/$path/arial.ttf";

  //@TODO saved all images in root of drupal
  $font = $_SERVER['DOCUMENT_ROOT']. "/arial.ttf";
  dsm($font);
  //dsm($_SERVER);




  ImageTTFText ($im, 20, 90, 50, 100, $grey, $font, 'Test');

  imagepng($im, 'test.png');

  //read it for base64
  $handle = fopen('test.png', "r");
  $binary = fread($handle, filesize('test.png'));
  fclose($handle);

  //ImageDestroy ($im);

  // echo getcwd();  -> /var/www/WORKSPACE_DRUPAL/KONTEXTWORK/spaces


  return '<img src="data:image/png;base64,' . base64_encode($binary) . '" />';
  //return base64_encode($image);


/*
ob_start();
        imagepng($image);
        printf('<img src="data:image/png;base64,%s"/>',
                base64_encode(ob_get_clean()));

        imagedestroy($myImage);*/


  //echo "<img src='test.png'/>";
  //ImageDestroy ($im);
  //exit();

}


/*
 * render the image
 *
 *
 *
 */

//@TODO implement admin settings page instead of hardcoded values.